### ISSUE TITLE
Save personal-biographer name update immediately

### ISSUE THREAD

**Issue by Whammo22** [MyLife-Services/mylife-maht#319]
When updating the name of personal-biographer it doesn't save and display in the chat window or header of bot immediately

1. Go to ['.'..](https://humanremembranceproject.org/members)
2. Click on Biographer bot in right column
3. Scroll down to type in open field and hit enter
4. Change to avatar or scrapbook bot
5. Click on Biographer Bot to see if new name is loaded in chat window

**Expected behavior**
In chat window and at the top of header of biographer the new bot name would be displayed.

**Screenshots**

![Image](https://github.com/user-attachments/assets/7e5beefc-e4ae-4a51-b7f4-1871f48af140)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 126 (64 Bit current version

**Smartphone (please complete the following information):**

**Additional context**
I didn't log out. I would expect it to update just as the Avatar bot updates without logging out.

**Comment by Mookse** [comment]
Absolutely - last known attempt was to have it update on **blur()** which is when it gets written to server
@Whammo22 it looks like this may well be unique to you due to our "fix" of your name
I am not experiencing this error, which is why I think it's specific to you, I think there may be two different biog bots assigned to you and they are breaking the interface
**update** @Whammo22 No, this is not limited to you, and this represents a disconnect between server and session memory, so becomes priority.

**Comment by Mookse** [comment]
``` js
originBot = mSanitize(updatedOriginBot ?? originBot)
avatar.bots[avatar.bots.findIndex(oBot=>oBot.id===botId)] = originBot
```

**Comment by Mookse** [comment]
- [x] backend: force avatar.bots[index] to originBot updates, which _were_ occurring
- [x] frontend: seems to be hung up, probably on mBots which isn't getting updated when bot_name locally is
