### ISSUE TITLE
Test Diary Bot Prototype

### ISSUE THREAD

**Issue by Mookse** [MyLife-Services/mylife-maht#349]
# Testing Diary Bot Prototype

Access and Test the [MyLife Diary Bot Prototype](https://chatgpt.com/g/g-rSCnLVUKd-mylife-diary-bot-prototype) OpenAI GPT version. Solicit for internal and external feedback.

- [x] Share link to test in Video comments
- [x] Also share in Slack
- [x] Work with @Vudum to establish pattern/channel to test and receive feedback (could be right here in Slack Comments?)
- [x] Tune and Adjust per feedback

**Comment by Vudum** [comment]
https://github.com/MyLife-Services/mylife-maht/issues/348
I have partially tested the mylife-diary-bot-prototype but couldn't finish as I have reached limit for using GPTs for now.
https://chatgpt.com/g/g-rSCnLVUKd-mylife-diary-bot-prototype

Following features are tested and works as expected:
Keep track of journal entries, Flags, interests.

Next, I will test following key features - Entry Prompting, Entry Summary Creation, Entry Summary Updating

**Comment by Vudum** [comment]
1. Entry Summary isn't created automatically after discussing a topic with prompts. The system keeps responding to questions, and when asked, it says the entry wasn't created but can be. 

As a member I expect the bot will create(at least ask the member if ok to create) an entry after 5 prompts while discussing on a single topic. **Functionality didn't work as expected.** 

3. To save an entry, member permission is required. If confirmed, the entry is saved. Otherwise entry created doesn't mean that it saved automatically.

4. Member Content Flagging worked well. I updated the entry with flagged content, and GPT recognized it, automatically updating the entry and reflecting changes in moods."

5. Data Privacy & Security->Works as expected.
6. After refreshing the page(mylife-diary-bot-prototype), entries are not remembered. **Not sure, if this is an expected behavior.**

**Comment by Vudum** [comment]
Additional testing has been completed, and here are the final issues observed:

1. 'If a member is not prompting or prompting takes more than 2 minutes, please suggest using a dynamic greeting.' This functionality did not work as expected; GPT did not greet the member even after an extended period of silence.

2. When switching between different GPTs or updating the GPT, previously provided entries are lost, and all input has to be re-entered."

With this, testing has been completed. I am closing this ticket. If we need a new ticket to investigate these issues if let me know @Mookse .

**Comment by Mookse** [comment]
That's great @Vudum -- I'll take the issues that you identified and roll them into this week's build for the series.

I think the only one you won't see in some format is the last one, that's a standard process for these bots and is intentional in their design. You would need to stay on the same conversation (MyLife is the inverse) to get remembered results. The refresh has to be the same, and honestly I've noticed inconsistencies at large, but if you click the correct conversation on the left, it will retain its "memory"
