### ISSUE TITLE
"I am sorry, the entire chat line went dark for a moment, please try again." message is shown in few cases

### ISSUE THREAD

**Issue by Vudum** [MyLife-Services/mylife-maht#390]
Case 1:
Login to MyLife and send a message straight away in the chat window.
"I am sorry, the entire chat line went dark for a moment, please try again." message is shown tot he sure.
![image](https://github.com/user-attachments/assets/56960349-4643-4d46-b6b9-63ceca5b20f4)

**Case 2**
Open a memory and close the popup window.
Ensure Active: <memory title is shown>
Send a message to update the title
or send a message to update the memory
Again same message is shown to the member.

**Comment by Vudum** [comment]
I figured out the issue, looks like we need to click on the biographer green button before we start modifying memories. Meaning, to update a memory, member should connect to biographer which happens only after clicking biographer green button which will turn into yellow.

**Comment by Vudum** [comment]
Is this behaviour expected? IMO, it's not expected as the memory is already active although member didn't click on the biographer.

**Comment by Mookse** [comment]
@Vudum This is definitely functioning as intended, and it's never a good thing, but it implies that we never got a return back from the OpenAI server.
That said, I'm wide open to changing the text or the experience of such instances. Note to @stratfordCircle that this might be ameliorated as we improve our MS instance, it could be dropping due to limited # of connections
